version: '3.8'

services:
  # PostgreSQL Database
  # db:
  #   image: postgres:15-alpine
  #   container_name: wbms_postgres_dev
  #   environment:
  #     POSTGRES_DB: wbms_db
  #     POSTGRES_USER: wbms_user
  #     POSTGRES_PASSWORD: wbms_password
  #   ports:
  #     - '5433:5432'
  #   volumes:
  #     - postgres_dev_data:/var/lib/postgresql/data
  #   networks:
  #     - wbms_network

  # Next.js Development
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: wbms_app_dev
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:newpassword@host.docker.internal:5432/wbms_db
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_USER=postgres
      #wbms_user
      - DB_PASSWORD=newpassword
      #wbms_password
      - DB_NAME=wbms_db
      - JWT_SECRET=supersecret_for_wbms
      - ENABLE_SAP_CRON=false
    # depends_on:
    #   - db
    networks:
      - wbms_network
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

# volumes:
#   postgres_dev_data:

networks:
  wbms_network:
    driver: bridge
